{% set name = "vizlo" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/glaserL/vizlo/archive/v1.0.1.tar.gz
  sha256: 766a4c9634b7bb8a5b979fadeb0d64fe7985ca41d70fed099e75eb2d5e5f4379

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - clingo >=5.4
    - networkx >=2.4
    - matplotlib-base >=3.2
    - numpy >=1.16
    - python-igraph >=0.8

test:
  imports:
    - tests
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/glaserL/vizlo
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Vizlo is a visualization extension for clingo.'
  description: |
    Vizlo is a visualization extension for clingo. 
    It is intended to help you visualize and potentially debug programs by showing an iterative simulation of the solving process.
  doc_url: https://github.com/glaserL/vizlo
  dev_url: https://github.com/glaserL/vizlo

extra:
  recipe-maintainers:
    - glaserL
